### ISSUE TITLE
Server hangs with chunked transfer and a length set to -1

### ISSUE THREAD

**Issue by ramanb** [http-kit/http-kit#137]
POST / HTTP/1.1
Host: 127.0.0.1
Transfer-Encoding: chunked

-100

Server hangs, logs spit

Fri Mar 28 14:36:44 EST 2014 [server-loop] ERROR - http server loop error, should not happen
java.lang.NegativeArraySizeException
        at org.httpkit.server.HttpDecoder.decode(HttpDecoder.java:95)
        at org.httpkit.server.HttpServer.decodeHttp(HttpServer.java:100)
        at org.httpkit.server.HttpServer.doRead(HttpServer.java:164)
        at org.httpkit.server.HttpServer.run(HttpServer.java:277)
        at java.lang.Thread.run(Thread.java:744)
Parameter Pollution

**Comment by ptaoussanis** [comment]
Could someone confirm if this is still an issue on master?

**Comment by kipz** [comment]
@ptaoussanis I have a failing test for this one. I'll see what I can do to fix.

**Comment by kipz** [comment]
On the face of it, this problem looks a bit wider than I thought. There are many things that we can do to the HTTP request to break main loop and stop the channel from being closed. AFAICT, there's no maximum timeout either, so just a normal (non-chunked) request with a Content-Length > 1 and no body leads to hanging. At the moment, I'm trying to unpick connection re-use from plain hanging channels....
