### ISSUE TITLE
IllegalMonitorStateException

### ISSUE THREAD

**Issue by jsab** [http-kit/http-kit#163]
After a little while, my server ends up using 100% process. The offending thread is this one:
```
"server-loop" prio=10 tid=0x00624138 nid=0xa98 runnable [0xa5a3e000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	- locked <0xa8773118> (a java.lang.IllegalMonitorStateException)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at java.lang.IllegalMonitorStateException.<init>(IllegalMonitorStateException.java:50)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:326)
	- locked <0xabba9a88> (a java.lang.Object)
	at org.httpkit.server.HttpServer.doRead(HttpServer.java:156)
	at org.httpkit.server.HttpServer.run(HttpServer.java:277)
	at java.lang.Thread.run(Thread.java:745)
```

This is on debian's openjdk-7-jre-headless:
```
OpenJDK Runtime Environment (IcedTea 2.5.1) (7u65-2.5.1-2~deb7u1)
OpenJDK Zero VM (build 24.65-b04, mixed mode)
```

**Comment by ptaoussanis** [comment]
Hi @jsab, busy performing issue triage - should this issue still be open?
