### ISSUE TITLE
NullPointerException on Mac OS X

### ISSUE THREAD

**Issue by kumarshantanu** [http-kit/http-kit#188]
Using http-kit 2.1.19 with Oracle Java 1.7.0_76 on Mac OS X Yosemite, I got the following stack trace when starting the server:

```text
Exception in thread "main" java.lang.ExceptionInInitializerError
	at sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:87)
	at sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:42)
	at java.nio.channels.Selector.open(Selector.java:227)
	at org.httpkit.server.HttpServer.<init>(HttpServer.java:59)
	at org.httpkit.server$run_server.invoke(server.clj:8)
	...
Caused by: java.lang.NullPointerException
	at sun.nio.ch.KQueueArrayWrapper.<clinit>(KQueueArrayWrapper.java:93)
	... 12 more
```

**Comment by venantius** [comment]
Code sample for what resulted in this would be helpful.

**Comment by kumarshantanu** [comment]
The code that caused it is fairly innocuous:

```clojure
(http-kit.server/run-server ring-handler hk-opts)
```

However, I was loading the namespace dynamically (instead of `(:require [...])`) that seems to have run into classloading issues. I avoided the issue by preloading some of the http-kit Java classes ahead of dynamic loading. I think this is not http-kit issue but rather Clojure classloader issue.

**Comment by ptaoussanis** [comment]
Hi Shantanu, busy doing issue triage: can this be closed?

**Comment by kumarshantanu** [comment]
Closed the issue as I am unable to verify this is really http-kit issue.
