### ISSUE TITLE
How to add self-defined header into headers when post ?

### ISSUE THREAD

**Issue by keroro520** [http-kit/http-kit#220]
It seems that the headers cannot include *self-defined header* when use `http/post` ?

Here is my code:

        (http/post url
            :headers {"Content-Type" "application/json; charset=utf-8" 
                               "self-defined-header" "hello" }
            :body (...))

Get error:

          Exception in thread "main" java.lang.NullPointerException, compiling:
        	at clojure.lang.Compiler.load(Compiler.java:7142)
        	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        	at clojure.main$load_script.invoke(main.clj:274)
        	at clojure.main$script_opt.invoke(main.clj:336)
        	at clojure.main$main.doInvoke(main.clj:420)
        	at clojure.lang.RestFn.invoke(RestFn.java:408)
        	at clojure.lang.Var.invoke(Var.java:379)
        	at clojure.lang.AFn.applyToHelper(AFn.java:154)
        	at clojure.lang.Var.applyTo(Var.java:700)
        	at clojure.main.main(main.java:37)
        Caused by: java.lang.NullPointerException
        	at org.httpkit.HeaderMap.encodeHeaders(HeaderMap.java:103)
        	at org.httpkit.client.HttpClient.encode(HttpClient.java:291)
        	at org.httpkit.client.HttpClient.exec(HttpClient.java:260)
        	at org.httpkit.client$request.doInvoke(client.clj:184)
        	at clojure.lang.RestFn.invoke(RestFn.java:423)
        	at org.httpkit.client$post.doInvoke(client.clj:200)
        	at clojure.lang.RestFn.invoke(RestFn.java:423)
        	at user$send_to.invoke(test.clj:37)                         # My File
        	at user$eval4.invoke(test.clj:43)
        	at clojure.lang.Compiler.eval(Compiler.java:6703)
        	at clojure.lang.Compiler.load(Compiler.java:7130)

**Comment by keroro520** [comment]
It my fault...it works .....................
