### ISSUE TITLE
Empty sequence response results in NullPointerException

### ISSUE THREAD

**Issue by leblowl** [http-kit/http-kit#247]
Test subject:

```clojure
(defn test []
  '())

# compojure route
(GET "/test" [] (test))
```

Exception:
```shell
Thu Jan 21 20:12:31 PST 2016 [worker-1] ERROR - GET /test
java.lang.NullPointerException
	at org.httpkit.HttpUtils.bodyBuffer(HttpUtils.java:102)
	at org.httpkit.HttpUtils.HttpEncode(HttpUtils.java:425)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I think it makes sense looking at the code in HttpUtils https://github.com/http-kit/http-kit/blob/b495e5fb3c44ac792654bcf4157993613bc579cd/src/java/org/httpkit/HttpUtils.java#L105-L115... feel free to let me know whatchya think

**Comment by ptaoussanis** [comment]
Hi Lucas, thanks for the report. PR to fix would be welcome!

**Comment by leblowl** [comment]
np, I will try to work on this, ty
