### ISSUE TITLE
ConcurrentModificationException while shutting down the server

### ISSUE THREAD

**Issue by danielcompton** [http-kit/http-kit#292]
I got this error today when shutting down: ConcurrentModificationException

```
HashMap.java:1429 in java.util.HashMap$HashIterator.nextNode
HashMap.java:1453 in java.util.HashMap$KeyIterator.next
Collections.java:1042 in java.util.Collections$UnmodifiableCollection$1.next
HttpServer.java:334 in org.httpkit.server.HttpServer.stop
server.clj:56 in org.httpkit.server$run_server$stop_server__11040.doInvoke
RestFn.java:137 in clojure.lang.RestFn.applyTo
AFunction.java:29 in clojure.lang.AFunction$1.doInvoke
RestFn.java:421 in clojure.lang.RestFn.invoke
ws.clj:24 in rethink_proxy.ws$start_web_server_BANG__STAR_$fn__11280.invoke
handler.clj:80 in rethink_proxy.handler$stop_web_server_BANG_.invoke
handler.clj:100 in rethink_proxy.handler$stop_BANG_.invoke
handler.clj:110 in rethink_proxy.handler$add_shutdown_hook$fn__20974.invoke
AFn.java:22 in clojure.lang.AFn.run
Thread.java:745 in java.lang.Thread.run
```

which seemed to correlate with

```
Thu May 19 06:38:08 UTC 2016 [server-loop] ERROR - increase :queue-size if this happens often
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@51db15c2 rejected from java.util.concurrent.ThreadPoolExecutor@65023842[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 92131]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
at org.httpkit.server.RingHandler.handle(RingHandler.java:203)
at org.httpkit.server.HttpServer.decodeWs(HttpServer.java:150)
at org.httpkit.server.HttpServer.doRead(HttpServer.java:186)
at org.httpkit.server.HttpServer.run(HttpServer.java:300)
at java.lang.Thread.run(Thread.java:745)
```

I'm not really sure if there's anything to do about this, nor how to reproduce it, so I'll close this issue, but have it on file for if others run into it too.

**Comment by harold** [comment]
With version `[http-kit "2.2.0"]` We also hit this today:
```
Caused by: java.util.ConcurrentModificationException: null
 at java.util.HashMap$HashIterator.nextNode (HashMap.java:1437)
    java.util.HashMap$KeyIterator.next (HashMap.java:1461)
    java.util.Collections$UnmodifiableCollection$1.next (Collections.java:1042)
    org.httpkit.server.HttpServer.stop (HttpServer.java:334)
    org.httpkit.server$run_server$stop_server__21228.doInvoke (server.clj:56)
```

Any workarounds, looking at other issues it seems that thread safety has been an issue with this code.
