### ISSUE TITLE
java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil

### ISSUE THREAD

**Issue by af-fess** [http-kit/http-kit#320]
I use `http-kit` for http POST/GET and other static sources for my front-end and everything works fine.

I try to implement Websocket with `http-kit`. I used [this guide](http://www.luminusweb.net/docs/websockets.md#http_kit) and this is what I did:

```
(:require
 ....
[org.httpkit.server :refer [run-server send! with-channel on-close on-receive]]
)

...

(GET "/ws" request (ws-handler request))

(defonce channels (atom #{}))

(defn connect! [channel]
  (info "channel open")
  (swap! channels conj channel))


(defn disconnect! [channel status]
  (info "channel closed:" status)
  (swap! channels #(remove #{channel} %)))

(defn notify-clients [msg]
  (doseq [channel @channels]
    (send! channel msg)))

(defn ws-handler [request]
  (info "FESS ::ws-handler" request)
  (with-channel request channel
                (connect! channel)
                (on-close channel (partial disconnect! channel))
                (on-receive channel #(notify-clients %))))

```

When I call from Javascript `var socket = new Socket("ws://localhost.com:3034/ws")`

I get an error:

```
java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil
```

Full stack trace:

```
17-01-07 10:01:27 Maxims-MacBook-Pro.local INFO [server-sdk-monitor.server:39] - channel open
2017-01-07 12:01:27.445:WARN:oejs.HttpChannel:qtp1494188138-12: /ws
java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560)
	at org.httpkit.server$eval3875$fn__3932$G__3866__3939.invoke(server.clj:63)
	at server_sdk_monitor.server$ws_handler.invokeStatic(server.clj:55)
	at server_sdk_monitor.server$ws_handler.invoke(server.clj:51)
	at server_sdk_monitor.server$fn__8616.invokeStatic(server.clj:112)
	at server_sdk_monitor.server$fn__8616.invoke(server.clj:112)
	at compojure.core$make_route$fn__3760.invoke(core.clj:99)
	at compojure.core$if_route$fn__3744.invoke(core.clj:45)
	at compojure.core$if_method$fn__3737.invoke(core.clj:30)
	at compojure.core$routing$fn__3766.invoke(core.clj:112)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:112)
	at compojure.core$routing.doInvoke(core.clj:109)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__3770.invoke(core.clj:117)
	at ring.middleware.params$wrap_params$fn__7104.invoke(params.clj:64)
	at ring.middleware.head$wrap_head$fn__4197.invoke(head.clj:32)
	at ring.middleware.cookies$wrap_cookies$fn__7026.invoke(cookies.clj:161)
	at ring.adapter.jetty$proxy_handler$fn__6885.invoke(jetty.clj:24)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

I use Intellij IDE and when I click on method `on-close` it redirects me to `httpkit//server.clj (on-close [ch callback]` so I have no idea why I get this method

This is my configuration:

```
$ lein deps :tree 
Possibly confusing dependencies found:
[ring/ring-core "1.4.0"] -> [org.clojure/tools.reader "0.9.1"]
 overrides
[com.taoensso/timbre "4.7.4"] -> [com.taoensso/encore "2.79.1"] -> [org.clojure/tools.reader "0.10.0"]

Consider using these exclusions:
[com.taoensso/timbre "4.7.4" :exclusions [org.clojure/tools.reader]]

[ring/ring-core "1.4.0"] -> [commons-io "2.4"]
 overrides
[clj-http "3.3.0"] -> [commons-io "2.5" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[clj-http "3.3.0" :exclusions [commons-io]]

 [cheshire "5.6.1"]
   [com.fasterxml.jackson.core/jackson-core "2.7.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.7.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.7.3"]
   [tigris "0.1.1"]
 [clj-http "3.3.0"]
   [org.apache.httpcomponents/httpclient "4.5.2" :exclusions [[org.clojure/clojure]]]
     [commons-logging "1.2"]
   [org.apache.httpcomponents/httpcore "4.4.5" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpmime "4.5.2" :exclusions [[org.clojure/clojure]]]
   [potemkin "0.4.3" :exclusions [[org.clojure/clojure]]]
     [clj-tuple "0.2.2"]
     [riddley "0.1.12"]
   [slingshot "0.12.2" :exclusions [[org.clojure/clojure]]]
 [clj-time "0.11.0"]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [clout "1.2.0" :scope "test"]
 [com.taoensso/timbre "4.7.4"]
   [com.taoensso/encore "2.79.1"]
     [com.taoensso/truss "1.3.5"]
   [io.aviso/pretty "0.1.30"]
 [compojure "1.1.8"]
   [org.clojure/tools.macro "0.1.0"]
 [consul-clojure "0.6.0-20160828.232719-2"]
   [camel-snake-kebab "0.3.1" :exclusions [[org.clojure/clojure] [com.keminglabs/cljx]]]
   [clj-http-lite "0.3.0" :exclusions [[org.clojure/clojure]]]
 [danlentz/clj-uuid "0.1.6"]
   [primitive-math "0.1.4"]
 [environ "1.0.0"]
 [http-kit "2.2.0"]
 [java-jdbc/dsl "0.1.3"]
 [mount "0.1.10"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/java.jdbc "0.6.2-alpha3"]
 [org.clojure/tools.namespace "0.2.4" :scope "test"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [org.postgresql/postgresql "9.2-1003-jdbc4"]
 [ring/ring-core "1.4.0"]
   [commons-fileupload "1.3.1"]
   [commons-io "2.4"]
   [crypto-equality "1.0.0"]
   [crypto-random "1.2.0"]
   [org.clojure/tools.reader "0.9.1"]
   [ring/ring-codec "1.0.0"]
 [ring/ring-jetty-adapter "1.4.0"]
   [org.eclipse.jetty/jetty-server "9.2.10.v20150310"]
     [javax.servlet/javax.servlet-api "3.1.0"]
     [org.eclipse.jetty/jetty-http "9.2.10.v20150310"]
       [org.eclipse.jetty/jetty-util "9.2.10.v20150310"]
     [org.eclipse.jetty/jetty-io "9.2.10.v20150310"]
   [ring/ring-servlet "1.4.0"]
 [rm-hull/ring-gzip-middleware "0.1.7"]
 [selmer "1.0.4"]
   [commons-codec "1.10"]
   [joda-time "2.9.2"]
   [json-html "0.3.9"]
     [hiccup "1.0.5"]
     [hiccups "0.3.0"]
       [org.clojure/clojurescript "0.0-2069"]
         [com.google.javascript/closure-compiler "v20130603"]
           [args4j "2.0.16"]
           [com.google.code.findbugs/jsr305 "1.3.9"]
           [com.google.guava/guava "14.0.1"]
           [com.google.protobuf/protobuf-java "2.4.1"]
           [org.json/json "20090211"]
         [org.clojure/data.json "0.2.3"]
         [org.clojure/google-closure-library "0.0-20130212-95c19e7f0f5f"]
           [org.clojure/google-closure-library-third-party "0.0-20130212-95c19e7f0f5f"]
         [org.mozilla/rhino "1.7R4"]
```

**Comment by venantius** [comment]
I believe what's happening here is that the return value of `(partial disconnect! channel)` is `nil`, which seems like a reasonable possibility given the code outlined here. Have you tried to verify that return value?

**Comment by af-fess** [comment]
@venantius yes, in method:

```
(defn connect! [channel]
 (info "connect! :: channel open: " channel)
 (swap! channels conj channel))
```

the `channel` is nil for some reason. I don't know why

**Comment by venantius** [comment]
I don't think the disconnect code is valid. For instance: 

```clojure
user=> ((partial #(remove #{'channel} %) #{'channel}))
()
```

This will have the effect of replacing the atom with an empty list, not a set.

**Comment by peterromfeldhk** [comment]
following the same guide ([almost](https://yogthos.net/posts/2015-06-11-Websockets.html)) getting the same error, i added the channel to on-connect! logging and got: 
```
17-02-02 09:20:24 spider.local INFO [handler] - channel open nil
java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil
```

something seems to be wrong with the binding and `channel` will be nil
```
(with-channel request channel
                (connect! channel)
                (on-close channel (partial disconnect! channel))
                (on-receive channel #(notify-clients %)))
```

**Comment by ptaoussanis** [comment]
Hi there! Is this still an ongoing issue for anyone, or can it be closed?

**Comment by paszek** [comment]
`No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil` 

It happens when I try `lein ring` instead of `org.httpkit.server/run-server`

**Comment by mcferren** [comment]
Also having this problem. I am booting with lein ring server.

**Comment by emiguelt** [comment]
Hi, 
Is there any update about this issue? I'm having the same problem when creating the websocket connection in a figwheel-based project.

    No implementation of method: :on-receive of protocol: #'org.httpkit.server/Channel found for class: nil
    java.lang.IllegalArgumentException: No implementation of method: :on-receive of protocol: #'org.httpkit.server/Channel found for class: nil

    at clojure.core$_cache_protocol_fn.invokeStatic (core_deftype.clj:568)
    clojure.core$_cache_protocol_fn.invoke (core_deftype.clj:560)
    org.httpkit.server$eval24184$fn__24228$G__24173__24235.invoke (server.clj:63)`

Initially I had the ring server configure, I change to http-kit server, but I still have the same error.

Thanks in advance for your help!

**Comment by wafflepie** [comment]
Hi, I managed to solve the issue by removing the lein-ring plugin and building the application by `lein uberjar` instead of `lein ring uberjar` (same goes for starting the server in development).

**Comment by pbaille** [comment]
Hello, I'm facing the same issue today, any progress on it? thank you in advance for your help

**Comment by dchacke** [comment]
+1

**Comment by skallet** [comment]
If you are using luminus, replace `[luminus-jetty "0.1.9"]` with `[luminus-immutant "0.2.5"]` in your `project.clj`.

**Comment by Kah0ona** [comment]
+1
