### ISSUE TITLE
Possible AOT issue

### ISSUE THREAD

**Issue by j0ni** [http-kit/http-kit#342]
I'm trying to get to the bottom of a problem I'm seeing which seems to be triggered by AOT compilation of code which includes http-kit. I've seen it in multiple repos now, and the stack traces all look like this:

```
Exception in thread "main" java.lang.IllegalArgumentException, compiling:(client.clj:85:19)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
	at clojure.lang.Compiler.eval(Compiler.java:6932)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at eulalie.platform$eval19631$loading__5569__auto____19632.invoke(platform.clj:1)
	at eulalie.platform$eval19631.invokeStatic(platform.clj:1)
	at eulalie.platform$eval19631.invoke(platform.clj:1)
... etc ...
```
Sometimes they go on much further, eventually leading to a `ns` form at the top of one of my files. Sometimes they're short, and where you see `eulalie.platform`, it leads straight to the top of one of my clojure source files.

NB This happens consistently in CI, but I haven't been able to reproduce it locally :(

The common denominator seems to be attempting to compile this form from `org.http-kit.client`:

```clojure
(def default-pool (let [max (.availableProcessors (Runtime/getRuntime))
                        queue (LinkedBlockingQueue.)
                        factory (PrefixThreadFactory. "client-worker-")]
                    (ThreadPoolExecutor. max max 60 TimeUnit/SECONDS queue factory)))
```

That form seems suspect to me in an AOT context, but I'm puzzled why I can't reproduce the problem when I run the build locally (I use `docker-compose build` to generate a container with an uberjar in it so I don't see a big opportunity for inconsistency).

At this point, I'm not sure it's a problem with `http-kit`, but I don't have a better starting point. Do you all have any thoughts or ideas about how to avoid this? 

I can provide more traces if it would help, but that's what they look like. The line number varies depending on which version of `http-kit` I pin at the top of my `project.clj` - Eulalie seems to depend on 2.1.18, but other traces show the line number reflecting the changed location of that form in 2.2.0, for example.

Hoping you will have some clues or ideas :)

edit to add: here's the cause exception trace which appears at the bottom of all of these:

```
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1307)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1230)
	at org.httpkit.client$fn__20128.invokeStatic(client.clj:88)
	at org.httpkit.client$fn__20128.invoke(client.clj:85)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
        ... 326 more
```

**Comment by j0ni** [comment]
Reading back over this, it occurs to me that `.availableProcessors` may not work in the LXC container environment that CircleCI provides. I'll test that theory.

**Comment by j0ni** [comment]
Here's [the line which throws the exception](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/concurrent/ThreadPoolExecutor.java?av=f#1307) according to grepcode.

**Comment by j0ni** [comment]
One last comment for now - I appear to have made this go away by using a different base container image for the compilation environment. Previously I was using `clojure:alpine`, and now I'm using `clojure:latest`. I do not understand what is causing this, but it seems like I have a workaround for now.

**Comment by kumarshantanu** [comment]
@j0ni Could it be the OpenJDK "mystery meat" issue? https://github.com/docker-library/openjdk/commit/00a9c5c080f2a5fd1510bc0716db7afe06cbd017

**Comment by venantius** [comment]
Could be any number of things; I'm not sure how the containers are built but it's entirely possible that you're picking up other underlying container differences between alpine and latest. I'd be inclined to file this with the folks at CircleCI and have them look into it.

Since this doesn't seem to be an http-kit issue, are you okay with us closing this issue?

**Comment by j0ni** [comment]
@venantius I guess I am, though I am not convinced it is a CircleCI issue either, since these images are not Circle's. Out of curiosity, when you say "any number of things", do you have any ideas to share? I'd appreciate any brainstorming here.

@kumarshantanu I guess it might, though that's a pretty huge bucket of entropy to throw at me :)

Thanks folks.

**Comment by venantius** [comment]
@j0ni sorry, I thought these might have been official images maintained by Circle. When I say "any number of things", I'm mostly thinking of things like differences in OS between Alpine and Debian Jessie.

**Comment by j0ni** [comment]
A small postscript - this works in Circle's `machine` executor on their 2.0 build system. The main difference from the perspective of this build is that they have an unpatched docker installed there, whereas on the 1.0 container they use a version which is old and patched for use inside LXC on BTRFS. There's a few moving parts there, and it's conceivable that any of those weirdnesses contributed to this problem.

So anyway, mystery meat indeed, but possibly not just of the OpenJDK variety.
