### ISSUE TITLE
prepare-response-headers in redirect causes ClassCastException

### ISSUE THREAD

**Issue by ethpran** [http-kit/http-kit#343]
java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.String
	at org.httpkit.HeaderMap.camelCase(HeaderMap.java:77)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

This seems to be happening because the headers of the 302 response I receive are [being reformatted to a clojure map](https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/client.clj#L226)  - see: [prepare-response-headers function](https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/client.clj#L34). The camelCase function expects a String type for the key of the map in takes as an argument. But we are forcing the key to be of type Keyword here before we feed it to this function, thus causing the exception. I am using version 2.2.0 of http-kit

**Comment by kwrooijen** [comment]
Ran into a similar issue. Would a PR with an option `:string-headers? true` be accepted? Or another name? @ptaoussanis

**Comment by ptaoussanis** [comment]
@kwrooijen Hi Kevin, it'd be helpful to first have a clearer description of the issue.

When exactly / under what conditions is this exception thrown? Can a reproducible example be provided?

Thanks!

**Comment by kwrooijen** [comment]
Minimal reproduction:
```clojure
(defn app [_request]
  {:status 200 :headers {:content-type "html/text"}})

(server/run-server app {:port 9999})
```

Then with curl:
```sh
curl localhost:9999
class clojure.lang.Keyword cannot be cast to class java.lang.String (clojure.lang.Keyword is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')%  
```

In my case (and I believe that of the OP) I'm using http-kit client to call an endpoint, and return those response headers. http-kit/client transforms the header keywords from strings to keywords. https://github.com/http-kit/http-kit/blob/9eac670a71f390a9e988deddfcf3203fa0970de7/src/org/httpkit/client.clj#L34-L35

The following function fails because it's expecting strings instead of keywords.
https://github.com/http-kit/http-kit/blob/9eac670a71f390a9e988deddfcf3203fa0970de7/src/java/org/httpkit/HttpUtils.java#L216-L229

For me it would be nice if I could skip the `prepare-response-headers` function, which would also give me a tiny bit of performance.
