### ISSUE TITLE
[bug] Using the client can cause OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by vizanto** [http-kit/http-kit#351]
Today I discovered a server crashing every few minutes. We `kill -9` the server on OutOfMemoryErrors.

Changing it to `kill -3` gave us some more details.

Turns out the http-kit client does not limit the size of arrays:

```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
Dumping heap to java_pid3347.hprof ...
Heap dump file created [6461833059 bytes in 47,990 secs]
#
# java.lang.OutOfMemoryError: Requested array size exceeds VM limit
# -XX:OnOutOfMemoryError="/nix/store/a03rvwzjlkvjpx0dnjb7mba9j1vwkrys-coreutils-8.22/bin/kill -3 %p"
#   Executing /usr/bin/sh -c "/nix/store/a03rvwzjlkvjpx0dnjb7mba9j1vwkrys-coreutils-8.22/bin/kill -3 3347"...
```

Stacktrace:
```
Sat Sep 23 10:25:30 UTC 2017 [client-loop] ERROR - select exception, should not happen
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at org.httpkit.DynamicBytes.expandIfNeeded(DynamicBytes.java:20)
        at org.httpkit.DynamicBytes.append(DynamicBytes.java:50)
        at org.httpkit.client.RespListener.unzipBody(RespListener.java:93)
        at org.httpkit.client.RespListener.onCompleted(RespListener.java:130)
        at org.httpkit.client.Request.finish(Request.java:51)
        at org.httpkit.client.HttpClient.doRead(HttpClient.java:163)
        at org.httpkit.client.HttpClient.run(HttpClient.java:426)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by reutsharabani** [comment]
Hi, I just opened a related issue https://github.com/http-kit/http-kit/issues/581#issue-2707287090

I fixed it **for my needs** by throwing an exception and using the same flow as IOException (sending an error downstream).
