### ISSUE TITLE
OpenJDK 11: "Select exception, should not happen"

### ISSUE THREAD

**Issue by cjohansen** [http-kit/http-kit#388]
I recently bumped a project from openjdk 8 to 11, and now an outgoing HTTPS request is failing with this exception:

    Fri Nov 30 12:55:02 UTC 2018 [client-loop] ERROR - select exception, should not happen
    java.lang.IllegalStateException: Client/Server mode has not yet been set.
    	at  java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:98)
    	at org.httpkit.client.HttpClient.finishConnect(HttpClient.java:395)
    	at org.httpkit.client.HttpClient.run(HttpClient.java:472)
    	at java.base/java.lang.Thread.run(Thread.java:834)

I built my app with OpenJDK 8, 10, and 11, and the code works fine on 8 and 10, but not 11. 

The request made is roughly:

```cli
(http/get "https://hooks.slack.com/services/..." {:query-params {:token "..."}})
```

http-kit version is 2.3.0

**Comment by claj** [comment]
This could be related to a change introduced even in openjdk 8 u181 where
sun.security.ssl.SSLSessionImpl seems to change its constructor, which leads to some NoSuchMethodError exception.

[https://www.mail-archive.com/openjdk@lists.launchpad.net/msg13114.html](https://www.mail-archive.com/openjdk@lists.launchpad.net/msg13114.html) mentions this stacktrace:

[https://launchpadlibrarian.net/396734572/java-update-8u181-b13-1ubuntu0.18.04.1-svn-failure.txt](https://launchpadlibrarian.net/396734572/java-update-8u181-b13-1ubuntu0.18.04.1-svn-failure.txt)

```
018-10-31 12:25:00.902 FATAL: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Lsun/security/ssl/SessionId;Ljava/lang/String;IZ)V
2018-10-31 12:25:00.903 java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Lsun/security/ssl/SessionId;Ljava/lang/String;IZ)V
2018-10-31 12:25:00.903 	at sun.security.ssl.ClientHandshaker.serverHello(ClientHandshaker.java:723)
2018-10-31 12:25:00.903 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:210)
2018-10-31 12:25:00.903 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
2018-10-31 12:25:00.903 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
2018-10-31 12:25:00.903 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
2018-10-31 12:25:00.903 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
2018-10-31 12:25:00.903 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
2018-10-31 12:25:00.903 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
```

It could of course be some other strange bug. Java's SSL-implementations are somewhat hostile.

**Comment by ryfow** [comment]
I've got a PR for that here https://github.com/http-kit/http-kit/pull/383

You could try it out and see if it works for you.

**Comment by ptaoussanis** [comment]
Merging Ryan's PR shortly, thanks

**Comment by ptaoussanis** [comment]
Just released https://github.com/http-kit/http-kit/releases/tag/v2.4.0-alpha1

**Comment by viniciusd** [comment]
Is it still at alpha @ptaoussanis ?

**Comment by viniciusd** [comment]
When should we expect 2.4.0 to be released @ptaoussanis @shenfeng ?
