### ISSUE TITLE
Misleading error message when http-kit receives a HTTP while shutting down

### ISSUE THREAD

**Issue by marcomorain** [http-kit/http-kit#398]
Thank you for HTTP, and thank you for the recent additions of the logging and event logging system - they were very easy to use, and very helpful. 💯 

https://github.com/http-kit/http-kit/blob/495219c40f86488351c6cc604df155a7a5b1a065/src/java/org/httpkit/server/RingHandler.java#L236-L238

I've been investigating a problem in my system where requests are being sent to a server that is being shutdown.

In this case, the code catches an `RejectedExecutionException` and returns an error to the user saying `Server is overloaded, please try later`, and message is logged saying `increase :queue-size if this happens often`.

This log message (`increase :queue-size`) was not helpful in my case, since the threadpool is shutting down, the queue is empty:

```
increase :queue-size if this happens often
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@573c38a6 rejected from java.util.concurrent.ThreadPoolExecutor@3eef1fe1[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 79225]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.httpkit.server.RingHandler.handle(RingHandler.java:234)
	at org.httpkit.server.HttpServer.decodeHttp(HttpServer.java:164)
	at org.httpkit.server.HttpServer.doRead(HttpServer.java:233)
	at org.httpkit.server.HttpServer.run(HttpServer.java:349)
	at java.lang.Thread.run(Thread.java:748)
```

Perhaps we could make http-kit check the status of the pool, or inspect the `RejectedExecutionException` and tailor the message for different scenarios.

I'm happy to contribute a patch if we decide that this is something we should change.

**Comment by ptaoussanis** [comment]
Related to https://github.com/http-kit/http-kit/pull/399

**Comment by ptaoussanis** [comment]
Hi Mark, just doing some issue triage.
I believe this can be closed with the merging of #399, but please feel free to re-open if I've misunderstood.

Thanks!
