### ISSUE TITLE
SNI client incompatible with JDK 17?

### ISSUE THREAD

**Issue by pmonks** [http-kit/http-kit#482]
Apologies if this issue report is poorly worded - I only have the vaguest of understandings of how SSL/TLS/SNI actually work.

The background is that I have [some code](https://github.com/pmonks/futbot/) (in production on JDK 11 for a little over a year) that has been working great.  That code enables SNI client support by default, as it accesses some web resources that fail if SNI is not used (i.e. the handshake fails without it).  It does this exactly as described [here](https://github.com/http-kit/http-kit#enabling-client-sni-support-disabled-by-default), as a top-level form in a "configuration bootstrap" namespace i.e. the root var gets altered before any HTTPS requests are made.

This code also uses another [third party library](https://github.com/IGJoshua/discljord/) that also makes use of httpkit - you will see that it's that library's use of httpkit that fails in the stack trace below, though I don't believe that has anything to do with that library itself.

With the recent release of JDK 17, I had a go at running the code on that version, and ran into the following NPE coming out of httpkit:
```
2021-09-28 10:23:34,416 ERROR [main] discljord.connections.impl - Failed to get websocket gateway
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "x" is null
	at clojure.lang.Numbers.ops(Numbers.java:1068)
	at clojure.lang.Numbers.gte(Numbers.java:263)
	at clojure.lang.Numbers.gte(Numbers.java:3981)
	at org.httpkit.sni_client$ssl_configurer.invokeStatic(sni_client.clj:44)
	at org.httpkit.sni_client$ssl_configurer.invoke(sni_client.clj:37)
	at org.httpkit.sni_client$ssl_configurer.invokeStatic(sni_client.clj:41)
	at org.httpkit.sni_client$ssl_configurer.invoke(sni_client.clj:37)
	at org.httpkit.client$make_client$reify__14498.configure(client.clj:148)
	at org.httpkit.client.HttpClient.exec(HttpClient.java:370)
	at org.httpkit.client$request.invokeStatic(client.clj:292)
	at org.httpkit.client$request.doInvoke(client.clj:180)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at org.httpkit.client$get.invokeStatic(client.clj:307)
	at org.httpkit.client$get.doInvoke(client.clj:307)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at discljord.connections.impl$get_websocket_gateway$fn__15593.invoke(impl.clj:460)
	at discljord.connections.impl$get_websocket_gateway.invokeStatic(impl.clj:459)
	at discljord.connections.impl$get_websocket_gateway.invoke(impl.clj:450)
	at discljord.connections$connect_bot_BANG_.invokeStatic(connections.clj:46)
	at discljord.connections$connect_bot_BANG_.doInvoke(connections.clj:23)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at futbot.config$eval21325$fn__21326.invoke(config.clj:81)
	at mount.core$record_BANG_.invokeStatic(core.cljc:74)
	at mount.core$record_BANG_.invoke(core.cljc:73)
	at mount.core$up$fn__14178.invoke(core.cljc:81)
	at mount.core$up.invokeStatic(core.cljc:80)
	at mount.core$up.invoke(core.cljc:78)
	at mount.core$bring.invokeStatic(core.cljc:247)
	at mount.core$bring.invoke(core.cljc:239)
	at mount.core$start.invokeStatic(core.cljc:289)
	at mount.core$start.doInvoke(core.cljc:281)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at futbot.main$_main$fn__25204.invoke(main.clj:71)
	at futbot.main$_main.invokeStatic(main.clj:58)
	at futbot.main$_main.doInvoke(main.clj:53)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
```

As I say, this code runs just fine on JDK 11, and if I remove the `(alter-var-root #'http/*default-client* (fn [_] sni-client/default-client))` line it also works in JDK 17 (though later HTTP requests fail with SSL handshake_failure errors).

Thoughts?

Environment:
* macOS Big Sur (11.6) - Intel
* OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
* Clojure 1.10.3
* discljord 1.2.3

**Comment by pmonks** [comment]
In a REPL I've also tested my own HTTPS calls (i.e. without the discljord library in the mix) and get the same NPE if the `alter-var-root` form is present.  If the `alter-var-root` form is not present it gives:
```
Execution error (SSLHandshakeException) at sun.security.ssl.Alert/createSSLException (Alert.java:131).
Received fatal alert: handshake_failure
```
(which is the original issue that led me to add the `alter-var-root` form back in the day)

**Comment by pmonks** [comment]
Ok a quick look at [sni_client.clj line 44](https://github.com/http-kit/http-kit/blob/v2.5.3/src/org/httpkit/sni_client.clj#L44) is pretty illuminating - that code is determining the JDK version, and probably just hasn't been updated for JDK 17 yet.

**Comment by pmonks** [comment]
Stand by - should have a PR for this shortly...

**Comment by ptaoussanis** [comment]
Manually merging your PR, thanks for the report and fix!
