### ISSUE TITLE
Client loop: SSL handshake failure

### ISSUE THREAD

**Issue by deobald** [http-kit/http-kit#487]
I'm suddenly seeing a mysterious error running in the background from my use of `httpkit.client`. It doesn't _appear_ to break client usage... but it's definitely disconcerting. Previous (successful) usage of httpkit has been on JDK 11 and earlier JDK 17 versions. Not sure if my recent bump to 17.0.3 is related. Unfortunately, it's not easy for me to roll back to the previous JDK 17 homebrew install.

* JDK Version: 17.0.3
* `lein version` => `Leiningen 2.9.5 on Java 17.0.3 OpenJDK 64-Bit Server VM`
* [http-kit "2.5.3"]
* Stacktrace follows:

```
Sat Apr 23 16:00:22 ADT 2022 [client-loop] ERROR - select exception, should not happen
java.lang.IllegalStateException: Client/Server mode has not yet been set.
	at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:98)
	at refactornrepl250SNAPSHOT.org.httpkit.client.HttpClient.finishConnect(HttpClient.java:395)
	at refactornrepl250SNAPSHOT.org.httpkit.client.HttpClient.run(HttpClient.java:472)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

My only usage of `org.httpkit.client` is in this file, on this one line: https://github.com/pariyatti/kosa/blob/6aead0781c281c6c62b700245990d230cb9fe13d/src/kuti/storage/open_uri.clj#L36 ... but this issue seems to be in a background thread anyway.

Hope this helps! Let me know if there's anything else I can do to help create a repro.

**Comment by deobald** [comment]
Uh, strange. Two things happened between the error and the fix:

1. I upgraded ring-jetty-adapter to `[ring/ring-jetty-adapter "1.9.5"]`
2. I accidentally killed Emacs. ;)

I'll close this now. Hopefully if anyone else runs into this mysterious error, one of the above actions helps.
