### ISSUE TITLE
Direct (non heap) memory leaks caused by serving bigger files (like videos)

### ISSUE THREAD

**Issue by kajism** [http-kit/http-kit#496]
When a file is bigger than the org.http-kit.memmap-file-threshold (20MB by default) then MappedByteBuffer is used, which is not so easy to GC and http-kit seems not to be trying to do so.

 See https://stackoverflow.com/questions/25238110/how-to-properly-close-mappedbytebuffer . 

This memory can, by Java default, grow up to the Heap size limit which means your app memory consumption can easily exceed twice the set maximum heap size and then serving large files stops.

As noted in org.http-kit.HttpUtils.java source in comment on line 111:
// serving file is better be done by Nginx

Or in this scenario, Undertow can be recommended.

**Comment by ptaoussanis** [comment]
@kajism Thanks for creating 👍 

> As noted in org.http-kit.HttpUtils.java source in comment on line 111:
> // serving file is better be done by Nginx

Correct, http-kit is in several areas not well optimised for large requests/responses.
The general advice is to use http-kit behind a proxy like nginx.

Use the proxy to do what it's good at (incl. serving static files - esp. large files, SSL termination, etc.), and use http-kit for dynamic application-level responses.

It'd be nice to have this advice directly in the README (PRs welcome).

Otherwise, PRs always welcome to help improve support for larger payloads.
A recent example includes https://github.com/http-kit/http-kit/pull/479

**Comment by kajism** [comment]
I have tried to create PR adding another JVM property which would enable/disable reading files using MappedByteBuffer in conjunction with the JVM property added in #479. Unfortunately the allocated direct memory grows anyway, so the problem seems to be deeper. Because I'm currently happy with Undertow, I give up.

**Comment by foromer4** [comment]
Having the same issue, 
getting ByeBuffer from S3 and passing them as is to http-kit response, cause a memory leak in direct memory.
Is there a way to use heap memory instead of direct memory?
Since not based on netty can't find documentation for any flags to achieve
 this

**Comment by rutchkiwi** [comment]
Chipping in here as I believe I'm experiencing the same issue.
I've got some endpoints that return rather large CSVs of data. (~25MB).
I do this using InputStreams, which as mentioned somewhere else buffers the whole steam in memory. This is not ideal, but for the size we're talking about that's ok. However, what is not "ok" is that when calling this many times, direct buffer pools keep growing and growing up to 200 mb (not sure why that exact number, heap size max is set to 210 m so might releated (-Xmx210m). Once I get up to that limit, I start getting `java.lang.OutOfMemoryError: Direct buffer memory`
Below is a screenshot from heroku showing the effect.

![Screenshot 2024-12-11 at 12 33 13](https://github.com/user-attachments/assets/e0aab301-b785-4fb9-a050-b8030bc97b88)

Here is a stack trace of when it errors - (probably not be when it leaks) 

```
11:41:17.182 ERROR [] backoffice.handler - http-kit: Error: GET /bing-feed.txt
java.lang.OutOfMemoryError: Direct buffer memory
 at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
 at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
 at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
 at java.base/sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:242)
 at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:164)
 at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
 at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:493)
 at org.httpkit.server.HttpServer.tryWrite(HttpServer.java:321)
 at org.httpkit.server.HttpServer.tryWrite(HttpServer.java:308)
 at org.httpkit.server.RespCallback.run(RespCallback.java:17)
 at org.httpkit.server.HttpHandler.run(RingHandler.java:129)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)
```

I have a hard time understanding the code there so any help is appreciated.
