### ISSUE TITLE
Problem in native-image and HttpUtils when using virtual threads

### ISSUE THREAD

**Issue by borkdude** [http-kit/http-kit#543]
When I run the below example with babashka:

``` clojure
(require '[org.httpkit.server :as server])

(defn app [_]
  {:status 200
   :body "Hello HTTP!"
   :headers {"Content-Type" "text/plain"}})

(server/run-server app {:port 8080
                        :worker-pool
                        (java.util.concurrent.Executors/newVirtualThreadPerTaskExecutor)
                        #_(java.util.concurrent.Executors/newFixedThreadPool 8)})

(println "Server started at http://localhost:8080")

@(promise) ;; wait for SIGINT
```

and I bombard the server with many requests like in this blogpost:

https://lemire.me/blog/2023/10/07/web-server-hello-world-benchmark-go-vs-node-js-vs-nim-vs-bun/
(also see https://twitter.com/lemire/status/1710538462460256437)

I'm getting to see:

```
java.util.NoSuchElementException
	at java.base@21/java.util.ArrayDeque.removeFirst(ArrayDeque.java:361)
	at java.base@21/java.util.ArrayDeque.pop(ArrayDeque.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.PrivilegedStack.pop(AccessControllerUtil.java:88)
	at java.base@21/java.security.AccessController.executePrivileged(AccessController.java:131)
	at java.base@21/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.base@21/sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
	at java.base@21/sun.util.resources.LocaleData.getDateFormatData(LocaleData.java:145)
	at java.base@21/java.text.DateFormatSymbols.initializeData(DateFormatSymbols.java:747)
	at java.base@21/java.text.DateFormatSymbols.<init>(DateFormatSymbols.java:151)
	at java.base@21/sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(DateFormatSymbolsProviderImpl.java:85)
	at java.base@21/java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:371)
	at java.base@21/java.text.DateFormatSymbols.getInstanceRef(DateFormatSymbols.java:361)
	at java.base@21/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:626)
	at org.httpkit.DateFormatter.initialValue(HttpUtils.java:26)
	at org.httpkit.DateFormatter.initialValue(HttpUtils.java:23)
	at java.base@21/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
	at java.base@21/java.lang.ThreadLocal.get(ThreadLocal.java:194)
	at java.base@21/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at org.httpkit.DateFormatter.getDate(HttpUtils.java:34)
	at org.httpkit.HttpUtils.HttpEncode(HttpUtils.java:473)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:135)
	at java.base@21/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base@21/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base@21/java.lang.VirtualThread.runWith(VirtualThread.java:341)
	at java.base@21/java.lang.VirtualThread.run(VirtualThread.java:311)
	at java.base@21/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:192)
```

There seems to be a problem with the `SimpleDateFormat` `ThreadLocal` in `HttpUtils` in combination with virtual threads.

But now that we are on JDK8 minimally, we can just replace this code with `java.time`.

I have found that replacing `HttpUtils$DateFormatter` with:

``` java
class DateFormatter {
    private static java.time.ZoneId GMT = java.time.ZoneId.of("GMT");
    private static java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.RFC_1123_DATE_TIME.withLocale(java.util.Locale.US);

    public static String getDate() {
        return java.time.ZonedDateTime.now(GMT).format(formatter);
    }
}
```

fixes the problem with GraalVM native image.

We could try to bother to hang on to `SimpleDateFormat` and get to the root issue with graal, but we might as well move on to `java.time` and forget about the old pre-8 stuff.

If you agree with this solution, I'd be happy to provide a PR and up my http-kit contributions ;).

**Comment by ptaoussanis** [comment]
@borkdude Hi Michiel, thanks for pinging about this!

Before we select a solution, do you have any idea what the underlying problem might be?

**Comment by borkdude** [comment]
I suspect it's an interplay between `ThreadLocal` and virtual threads, but I'm not exactly sure. My hunch would be that the `SimpleDataFormat` class isn't as well tested as the newer `java.time` API with virtual threads.

(I updated the proposed Java solution)

**Comment by borkdude** [comment]
Anyway, getting rid of `ThreadLocal` would be beneficial for virtual threads anyway:

> Virtual threads support thread-local variables ([ThreadLocal](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ThreadLocal.html)) and inheritable thread-local variables ([InheritableThreadLocal](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/InheritableThreadLocal.html)), just like platform threads, so they can run existing code that uses thread locals. However, because virtual threads can be very numerous, use thread locals only after careful consideration.

https://openjdk.org/jeps/444

**Comment by ptaoussanis** [comment]
PR welcome, thanks Michiel 👍

**Comment by borkdude** [comment]
There we go: https://github.com/http-kit/http-kit/pull/544

**Comment by ptaoussanis** [comment]
Thanks! Busy working on http-kit, will get it merged in the next couple days 👍

**Comment by ptaoussanis** [comment]
Merged manually, thanks Michiel!

**Comment by borkdude** [comment]
Cool, as soon as you have a new beta, I'll bump in babashka since I want to publish some benchmarks which should be reproducible by others :)

**Comment by ptaoussanis** [comment]
👍 Just a heads-up that the next release will also include a full benchmark suite.

**Comment by borkdude** [comment]
Cool :)

**Comment by ptaoussanis** [comment]
Have just pushed [beta2](https://github.com/http-kit/http-kit/releases/tag/v2.8.0-beta2) 👍
See [here](https://github.com/http-kit/http-kit/wiki/4-Benchmarking) for the benchmarking info.

Improvements to the bench suite, and/or additional results very welcome!
