### ISSUE TITLE
Exceptions when server is under load

### ISSUE THREAD

**Issue by jakepearson** [http-kit/http-kit#73]
Hi,
I am seeing this exception periodically when the server is under load.  I believe it might happen when the handler is slow (maybe a queueing problem?).

    Tue Jul 23 11:42:37 MDT 2013 [server-loop] ERROR - http server loop error, should not happen
    java.nio.channels.CancelledKeyException
    	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:55)
    	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:69)
    	at sun.nio.ch.KQueueSelectorImpl.updateSelectedKeys(KQueueSelectorImpl.java:105)
    	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:74)
    	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)   
    	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
    	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:84)
    	at org.httpkit.server.HttpServer.run(HttpServer.java:232)
    	at java.lang.Thread.run(Thread.java:680)

**Comment by ptaoussanis** [comment]
Closing for now, please feel free to reopen if anyone's still having trouble with this using the [latest http-kit release](https://github.com/http-kit/http-kit/releases).
